<Diagramm>
    <Colors>
        <Anzahl>23</Anzahl>
        <Color0>
            <B>255</B>
            <G>0</G>
            <Name>blau</Name>
            <R>0</R>
        </Color0>
        <Color1>
            <B>221</B>
            <G>212</G>
            <Name>blaugrau</Name>
            <R>175</R>
        </Color1>
        <Color10>
            <B>192</B>
            <G>192</G>
            <Name>hellgrau</Name>
            <R>192</R>
        </Color10>
        <Color11>
            <B>255</B>
            <G>0</G>
            <Name>kamesinrot</Name>
            <R>255</R>
        </Color11>
        <Color12>
            <B>0</B>
            <G>200</G>
            <Name>orange</Name>
            <R>255</R>
        </Color12>
        <Color13>
            <B>255</B>
            <G>247</G>
            <Name>pastell-blau</Name>
            <R>211</R>
        </Color13>
        <Color14>
            <B>186</B>
            <G>245</G>
            <Name>pastell-gelb</Name>
            <R>255</R>
        </Color14>
        <Color15>
            <B>234</B>
            <G>255</G>
            <Name>pastell-gr&amp;uuml;n</Name>
            <R>211</R>
        </Color15>
        <Color16>
            <B>255</B>
            <G>211</G>
            <Name>pastell-lila</Name>
            <R>244</R>
        </Color16>
        <Color17>
            <B>191</B>
            <G>165</G>
            <Name>pastell-rot</Name>
            <R>244</R>
        </Color17>
        <Color18>
            <B>175</B>
            <G>175</G>
            <Name>pink</Name>
            <R>255</R>
        </Color18>
        <Color19>
            <B>0</B>
            <G>0</G>
            <Name>rot</Name>
            <R>255</R>
        </Color19>
        <Color2>
            <B>61</B>
            <G>125</G>
            <Name>braun</Name>
            <R>170</R>
        </Color2>
        <Color20>
            <B>0</B>
            <G>0</G>
            <Name>schwarz</Name>
            <R>0</R>
        </Color20>
        <Color21>
            <B>255</B>
            <G>255</G>
            <Name>t&amp;uuml;rkis</Name>
            <R>0</R>
        </Color21>
        <Color22>
            <B>255</B>
            <G>255</G>
            <Name>wei&amp;szlig;</Name>
            <R>255</R>
        </Color22>
        <Color3>
            <B>64</B>
            <G>64</G>
            <Name>dunkelgrau</Name>
            <R>64</R>
        </Color3>
        <Color4>
            <B>84</B>
            <G>132</G>
            <Name>dunkelgr&amp;uuml;n</Name>
            <R>94</R>
        </Color4>
        <Color5>
            <B>0</B>
            <G>255</G>
            <Name>gelb</Name>
            <R>255</R>
        </Color5>
        <Color6>
            <B>0</B>
            <G>225</G>
            <Name>goldgelb</Name>
            <R>255</R>
        </Color6>
        <Color7>
            <B>128</B>
            <G>128</G>
            <Name>grau</Name>
            <R>128</R>
        </Color7>
        <Color8>
            <B>0</B>
            <G>255</G>
            <Name>gr&amp;uuml;n</Name>
            <R>0</R>
        </Color8>
        <Color9>
            <B>255</B>
            <G>212</G>
            <Name>hellblau</Name>
            <R>191</R>
        </Color9>
    </Colors>
    <ComplexIndices>
        <IndexCount>0</IndexCount>
    </ComplexIndices>
    <DataSource>
        <Import>
            <DBName></DBName>
            <Description></Description>
            <Domains>false</Domains>
            <Driver></Driver>
            <Name></Name>
            <Referenzen>false</Referenzen>
            <User></User>
        </Import>
        <Update>
            <DBMode>MYSQL</DBMode>
            <DBName></DBName>
            <Description></Description>
            <DomainFaehig>false</DomainFaehig>
            <Driver></Driver>
            <FkNotNullBeachten>false</FkNotNullBeachten>
            <Name></Name>
            <ReferenzenSetzen>false</ReferenzenSetzen>
            <User></User>
        </Update>
    </DataSource>
    <DefaultComment>
        <Anzahl>0</Anzahl>
    </DefaultComment>
    <Domains>
        <Anzahl>8</Anzahl>
        <Domain0>
            <Datatype>12</Datatype>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A type to represent account numbers.</Kommentar>
            <Length>20</Length>
            <NKS>0</NKS>
            <Name>AccountNumber</Name>
        </Domain0>
        <Domain1>
            <Datatype>4</Datatype>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>An amount of cents.</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Amount</Name>
        </Domain1>
        <Domain2>
            <Datatype>12</Datatype>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A type for bank identification numbers.</Kommentar>
            <Length>20</Length>
            <NKS>0</NKS>
            <Name>BankIdentificationNumber</Name>
        </Domain2>
        <Domain3>
            <Datatype>4</Datatype>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A type to represent boolean values.</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Boolean</Name>
        </Domain3>
        <Domain4>
            <Datatype>4</Datatype>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A domain for primary keys.</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Ident</Name>
        </Domain4>
        <Domain5>
            <Datatype>12</Datatype>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A domain for names.</Kommentar>
            <Length>100</Length>
            <NKS>0</NKS>
            <Name>Name</Name>
        </Domain5>
        <Domain6>
            <Datatype>12</Datatype>
            <History>SEMSTRAL, </History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A type for periode enum representations (YEAR, SEMESTRAL, QUARTER, MONTH).</Kommentar>
            <Length>10</Length>
            <NKS>0</NKS>
            <Name>Periode</Name>
        </Domain6>
        <Domain7>
            <Datatype>12</Datatype>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A domain for reasons of payment.</Kommentar>
            <Length>255</Length>
            <NKS>0</NKS>
            <Name>ReasonOfPayment</Name>
        </Domain7>
    </Domains>
    <Factories>
        <Object>archimedes.legacy.scheme.DefaultObjectFactory</Object>
    </Factories>
    <Pages>
        <PerColumn>5</PerColumn>
        <PerRow>10</PerRow>
    </Pages>
    <Parameter>
        <AdditionalSQLScriptListener></AdditionalSQLScriptListener>
        <Applicationname>Kroisos</Applicationname>
        <AufgehobeneAusblenden>false</AufgehobeneAusblenden>
        <Autor>ollie</Autor>
        <Basepackagename>kroisos</Basepackagename>
        <CodeFactoryClassName></CodeFactoryClassName>
        <Codebasispfad>.\</Codebasispfad>
        <DBVersionDBVersionColumn></DBVersionDBVersionColumn>
        <DBVersionDescriptionColumn></DBVersionDescriptionColumn>
        <DBVersionTablename></DBVersionTablename>
        <History>@changed OLI 01.03.2013 - Added.</History>
        <Kommentar>The model of the Kroisos application.</Kommentar>
        <Name>Kroisos</Name>
        <PflichtfelderMarkieren>false</PflichtfelderMarkieren>
        <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
        <SchemaName></SchemaName>
        <Schriftgroessen>
            <Tabelleninhalte>12</Tabelleninhalte>
            <Ueberschriften>24</Ueberschriften>
            <Untertitel>12</Untertitel>
        </Schriftgroessen>
        <Scripte>
            <AfterWrite>&amp;lt;null&amp;gt;</AfterWrite>
        </Scripte>
        <TechnischeFelderAusgrauen>false</TechnischeFelderAusgrauen>
        <UdschebtiBaseClassName></UdschebtiBaseClassName>
        <Version>1</Version>
        <Versionsdatum>01.03.2013</Versionsdatum>
        <Versionskommentar>&amp;lt;null&amp;gt;</Versionskommentar>
    </Parameter>
    <Stereotype>
        <Anzahl>0</Anzahl>
    </Stereotype>
    <Tabellen>
        <Anzahl>7</Anzahl>
        <Tabelle0>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>pastell-blau</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar>A representation of accounts.</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Account</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>5</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The key of the account.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Bank</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>RIGHT</Direction0>
                        <Direction1>LEFT</Direction1>
                        <Offset0>150</Offset0>
                        <Offset1>25</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>Bank</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>RIGHT</Direction0>
                                <Direction1>LEFT</Direction1>
                                <Name>Main</Name>
                                <Offset0>150</Offset0>
                                <Offset1>25</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Owner</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>RIGHT</Direction0>
                        <Direction1>LEFT</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>Owner</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>RIGHT</Direction0>
                                <Direction1>LEFT</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Name</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>A name for the account.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>AccountName</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte3>
                <Spalte4>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>AccountNumber</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The account number.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>AccountNumber</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte4>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>100</X>
                    <Y>100</Y>
                </View0>
            </Views>
        </Tabelle0>
        <Tabelle1>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>pastell-rot</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Bank</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>3</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen>LIST: Account</Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The key of the bank.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>BankIdentificationNumber</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>BankIdentificationNumber</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter>NOT-EMPTY</Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Name</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The name of the bank.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>BankName</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter>NOT-EMPTY</Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>525</X>
                    <Y>225</Y>
                </View0>
            </Views>
        </Tabelle1>
        <Tabelle2>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>goldgelb</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar>The representation of account owners.</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Owner</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>3</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen>LIST: Account</Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The id of the owner.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Name</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The first name of the owner.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>FirstName</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Name</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The last name of the owner.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>LastName</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>525</X>
                    <Y>100</Y>
                </View0>
            </Views>
        </Tabelle2>
        <Tabelle3>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>hellblau</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar>The representation of the acount entries.</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>AccountEntry</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>5</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen>LIST: BudgetEntry</Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The id of the account entry.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The account whose balance is decreased by the account of the entry.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Creadit</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>UP</Direction0>
                        <Direction1>DOWN</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>Account</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>UP</Direction0>
                                <Direction1>DOWN</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The account whose balance is increased by the entry.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Debit</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>UP</Direction0>
                        <Direction1>DOWN</Direction1>
                        <Offset0>50</Offset0>
                        <Offset1>50</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>Account</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>UP</Direction0>
                                <Direction1>DOWN</Direction1>
                                <Name>Main</Name>
                                <Offset0>50</Offset0>
                                <Offset1>50</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>A flag which can be used to mark account entries as open.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Invalid</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte3>
                <Spalte4>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>ReasonOfPayment</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The reason of payment for the account entry,.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>ReasonOfPayment</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte4>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>100</X>
                    <Y>375</Y>
                </View0>
            </Views>
        </Tabelle3>
        <Tabelle4>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>dunkelgr&amp;uuml;n</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar>Representation of a budget.</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Budget</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>3</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The primary key of the budget.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Name</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The name of the budget.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>BudgetName</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Amount</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>MaximumAmount</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>100</X>
                    <Y>800</Y>
                </View0>
            </Views>
        </Tabelle4>
        <Tabelle5>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>pastell-gr&amp;uuml;n</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar>A single budget entry which represents an amount of an account entry which is to book on the related budget.</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>BudgetEntry</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>3</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The account entry which the budget entry is assigned to.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>AccountEntry</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>UP</Direction0>
                        <Direction1>DOWN</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>AccountEntry</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>UP</Direction0>
                                <Direction1>DOWN</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The budget which the entry is related to.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Budget</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>DOWN</Direction0>
                        <Direction1>UP</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>Budget</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>DOWN</Direction0>
                                <Direction1>UP</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Amount</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The amount which is to book for the budget.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Amount</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>100</X>
                    <Y>600</Y>
                </View0>
            </Views>
        </Tabelle5>
        <Tabelle6>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>blaugrau</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History>@changed OLI 01.03.2013 - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar>A preriodic account entry.</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>PeriodicAccountEntry</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>2</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI 01.03.2013 - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The primary key of the periodic account entry.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <Referenz>
                        <Direction0>LEFT</Direction0>
                        <Direction1>RIGHT</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>AccountEntry</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>LEFT</Direction0>
                                <Direction1>RIGHT</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Periode</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>SEMSTRAL, </History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar>The periode which is valid for the periodic entry.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Periode</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>525</X>
                    <Y>375</Y>
                </View0>
            </Views>
        </Tabelle6>
    </Tabellen>
    <Views>
        <Anzahl>1</Anzahl>
        <View0>
            <Beschreibung>Diese Sicht beinhaltet alle Tabellen des Schemas</Beschreibung>
            <Name>Main</Name>
            <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
            <Tabelle0>Account</Tabelle0>
            <Tabelle1>Bank</Tabelle1>
            <Tabelle2>Owner</Tabelle2>
            <Tabelle3>AccountEntry</Tabelle3>
            <Tabelle4>Budget</Tabelle4>
            <Tabelle5>BudgetEntry</Tabelle5>
            <Tabelle6>PeriodicAccountEntry</Tabelle6>
            <Tabellenanzahl>7</Tabellenanzahl>
            <TechnischeSpaltenVerstecken>false</TechnischeSpaltenVerstecken>
        </View0>
    </Views>
</Diagramm>
