<Diagramm>
    <AdditionalSQLCode>
        <SQLCode>
            <AdditionalSQLCodePostChanging></AdditionalSQLCodePostChanging>
            <AdditionalSQLCodePostReducing></AdditionalSQLCodePostReducing>
            <AdditionalSQLCodePreChanging></AdditionalSQLCodePreChanging>
            <AdditionalSQLCodePreExtending></AdditionalSQLCodePreExtending>
        </SQLCode>
    </AdditionalSQLCode>
    <Colors>
        <Anzahl>23</Anzahl>
        <Color0>
            <B>255</B>
            <G>0</G>
            <Name>blau</Name>
            <R>0</R>
        </Color0>
        <Color1>
            <B>221</B>
            <G>212</G>
            <Name>blaugrau</Name>
            <R>175</R>
        </Color1>
        <Color10>
            <B>192</B>
            <G>192</G>
            <Name>hellgrau</Name>
            <R>192</R>
        </Color10>
        <Color11>
            <B>255</B>
            <G>0</G>
            <Name>kamesinrot</Name>
            <R>255</R>
        </Color11>
        <Color12>
            <B>0</B>
            <G>200</G>
            <Name>orange</Name>
            <R>255</R>
        </Color12>
        <Color13>
            <B>255</B>
            <G>247</G>
            <Name>pastell-blau</Name>
            <R>211</R>
        </Color13>
        <Color14>
            <B>186</B>
            <G>245</G>
            <Name>pastell-gelb</Name>
            <R>255</R>
        </Color14>
        <Color15>
            <B>234</B>
            <G>255</G>
            <Name>pastell-gr&amp;uuml;n</Name>
            <R>211</R>
        </Color15>
        <Color16>
            <B>255</B>
            <G>211</G>
            <Name>pastell-lila</Name>
            <R>244</R>
        </Color16>
        <Color17>
            <B>191</B>
            <G>165</G>
            <Name>pastell-rot</Name>
            <R>244</R>
        </Color17>
        <Color18>
            <B>175</B>
            <G>175</G>
            <Name>pink</Name>
            <R>255</R>
        </Color18>
        <Color19>
            <B>0</B>
            <G>0</G>
            <Name>rot</Name>
            <R>255</R>
        </Color19>
        <Color2>
            <B>61</B>
            <G>125</G>
            <Name>braun</Name>
            <R>170</R>
        </Color2>
        <Color20>
            <B>0</B>
            <G>0</G>
            <Name>schwarz</Name>
            <R>0</R>
        </Color20>
        <Color21>
            <B>255</B>
            <G>255</G>
            <Name>t&amp;uuml;rkis</Name>
            <R>0</R>
        </Color21>
        <Color22>
            <B>255</B>
            <G>255</G>
            <Name>wei&amp;szlig;</Name>
            <R>255</R>
        </Color22>
        <Color3>
            <B>64</B>
            <G>64</G>
            <Name>dunkelgrau</Name>
            <R>64</R>
        </Color3>
        <Color4>
            <B>84</B>
            <G>132</G>
            <Name>dunkelgr&amp;uuml;n</Name>
            <R>94</R>
        </Color4>
        <Color5>
            <B>0</B>
            <G>255</G>
            <Name>gelb</Name>
            <R>255</R>
        </Color5>
        <Color6>
            <B>0</B>
            <G>225</G>
            <Name>goldgelb</Name>
            <R>255</R>
        </Color6>
        <Color7>
            <B>128</B>
            <G>128</G>
            <Name>grau</Name>
            <R>128</R>
        </Color7>
        <Color8>
            <B>0</B>
            <G>255</G>
            <Name>gr&amp;uuml;n</Name>
            <R>0</R>
        </Color8>
        <Color9>
            <B>255</B>
            <G>212</G>
            <Name>hellblau</Name>
            <R>191</R>
        </Color9>
    </Colors>
    <ComplexIndices>
        <IndexCount>0</IndexCount>
    </ComplexIndices>
    <DataSource>
        <Import>
            <DBName></DBName>
            <Description></Description>
            <Domains>false</Domains>
            <Driver></Driver>
            <Name></Name>
            <Referenzen>false</Referenzen>
            <User></User>
        </Import>
    </DataSource>
    <DatabaseConnections>
        <Count>1</Count>
        <DatabaseConnection0>
            <DBExecMode>MYSQL</DBExecMode>
            <Driver>com.mysql.jdbc.Driver</Driver>
            <Name>Productive database</Name>
            <Quote></Quote>
            <SetDomains>false</SetDomains>
            <SetNotNull>false</SetNotNull>
            <SetReferences>false</SetReferences>
            <URL>jdbc:mysql://messene/platon</URL>
            <UserName>platon</UserName>
        </DatabaseConnection0>
    </DatabaseConnections>
    <DefaultComment>
        <Anzahl>0</Anzahl>
    </DefaultComment>
    <Domains>
        <Anzahl>14</Anzahl>
        <Domain0>
            <Datatype>4</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A boolean value in number format. 0 means false, any other value is true.</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Boolean</Name>
            <Parameters></Parameters>
        </Domain0>
        <Domain1>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>This type is for descriptions in the meaning of names of data records.</Kommentar>
            <Length>100</Length>
            <NKS>0</NKS>
            <Name>Description</Name>
            <Parameters></Parameters>
        </Domain1>
        <Domain10>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>21</Length>
            <NKS>0</NKS>
            <Name>Password</Name>
            <Parameters></Parameters>
        </Domain10>
        <Domain11>
            <Datatype>4</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Portnumber</Name>
            <Parameters></Parameters>
        </Domain11>
        <Domain12>
            <Datatype>4</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Sorting</Name>
            <Parameters></Parameters>
        </Domain12>
        <Domain13>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A token, that describes the record in a short form.</Kommentar>
            <Length>20</Length>
            <NKS>0</NKS>
            <Name>Token</Name>
            <Parameters></Parameters>
        </Domain13>
        <Domain2>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>255</Length>
            <NKS>0</NKS>
            <Name>Filename</Name>
            <Parameters></Parameters>
        </Domain2>
        <Domain3>
            <Datatype>-5</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A GLI is a global local identificator. Fields of this type are used to store comprehensive ids (across more than one databases).</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>GLI</Name>
            <Parameters></Parameters>
        </Domain3>
        <Domain4>
            <Datatype>-5</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>This type should be used for key data fields.</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Ident</Name>
            <Parameters></Parameters>
        </Domain4>
        <Domain5>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>255</Length>
            <NKS>0</NKS>
            <Name>LongDescription</Name>
            <Parameters></Parameters>
        </Domain5>
        <Domain6>
            <Datatype>-5</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>A type to store more precise manner, than the PTimestamp domain. LongPTimestamps include millis additionally. The format is: YYYYMMDDHHMMSSsss.</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>LongPTimestamp</Name>
            <Parameters></Parameters>
        </Domain6>
        <Domain7>
            <Datatype>-1</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Longtext</Name>
            <Parameters></Parameters>
        </Domain7>
        <Domain8>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>This field contains the name of the Workstation, where the data record has been changed.</Kommentar>
            <Length>40</Length>
            <NKS>0</NKS>
            <Name>PCName</Name>
            <Parameters></Parameters>
        </Domain8>
        <Domain9>
            <Datatype>2</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar>Data fields of this type contain time informations in the following format: YYYYMMDDHHMMSS.</Kommentar>
            <Length>14</Length>
            <NKS>0</NKS>
            <Name>PTimestamp</Name>
            <Parameters></Parameters>
        </Domain9>
    </Domains>
    <Factories>
        <Object>archimedes.legacy.scheme.DefaultObjectFactory</Object>
    </Factories>
    <Pages>
        <PerColumn>5</PerColumn>
        <PerRow>10</PerRow>
    </Pages>
    <Parameter>
        <AdditionalSQLScriptListener></AdditionalSQLScriptListener>
        <Applicationname>TestModel</Applicationname>
        <AufgehobeneAusblenden>false</AufgehobeneAusblenden>
        <Autor>ollie</Autor>
        <Basepackagename>testmodel</Basepackagename>
        <CodeFactoryClassName></CodeFactoryClassName>
        <Codebasispfad>~/codetmp/</Codebasispfad>
        <DBVersionDBVersionColumn></DBVersionDBVersionColumn>
        <DBVersionDescriptionColumn></DBVersionDescriptionColumn>
        <DBVersionTablename></DBVersionTablename>
        <History></History>
        <Kommentar>Ein kleines Archimedesmodell f&amp;uuml;r den Unittest.</Kommentar>
        <Name>TestModel 2</Name>
        <Optionen>
            <Anzahl>0</Anzahl>
        </Optionen>
        <PflichtfelderMarkieren>false</PflichtfelderMarkieren>
        <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
        <RelationColorExternalTables>java.awt.Color[r=192,g=192,b=192]</RelationColorExternalTables>
        <RelationColorRegular>java.awt.Color[r=0,g=0,b=0]</RelationColorRegular>
        <SchemaName></SchemaName>
        <Schriftgroessen>
            <Tabelleninhalte>12</Tabelleninhalte>
            <Ueberschriften>24</Ueberschriften>
            <Untertitel>12</Untertitel>
        </Schriftgroessen>
        <Scripte>
            <AfterWrite>&amp;lt;null&amp;gt;</AfterWrite>
        </Scripte>
        <TechnischeFelderAusgrauen>true</TechnischeFelderAusgrauen>
        <TransienteFelderAusgrauen>false</TransienteFelderAusgrauen>
        <UdschebtiBaseClassName></UdschebtiBaseClassName>
        <Version>2</Version>
        <Versionsdatum>09.12.2008</Versionsdatum>
        <Versionskommentar>:o)</Versionskommentar>
    </Parameter>
    <Sequences>
        <Count>0</Count>
    </Sequences>
    <Stereotype>
        <Anzahl>4</Anzahl>
        <Stereotype0>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>Diese Stereotype kennzeichnet eine Tabelle, deren Datens&amp;auml;tze nicht gel&amp;ouml;scht, sondern lediglich deaktiviert werden sollen.</Kommentar>
            <Name>Deactivatable</Name>
        </Stereotype0>
        <Stereotype1>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>Diese Stereotype kennzeichnet eine Tabelle, deren Datens&amp;auml;tze nicht gel&amp;ouml;scht, sondern lediglich deaktiviert werden sollen.</Kommentar>
            <Name>Deaktivierbar</Name>
        </Stereotype1>
        <Stereotype2>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>-/-</Kommentar>
            <Name>System</Name>
        </Stereotype2>
        <Stereotype3>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>-/-</Kommentar>
            <Name>Test</Name>
        </Stereotype3>
    </Stereotype>
    <Tabellen>
        <Anzahl>4</Anzahl>
        <Tabelle0>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Attribute>OPTIONAL</Attribute>
                        <Spalte>Description</Spalte>
                        <Tabelle>Table01</Tabelle>
                    </Member0>
                    <Member1>
                        <Attribute>OPTIONAL</Attribute>
                        <Spalte>Token</Spalte>
                        <Tabelle>Table01</Tabelle>
                    </Member1>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Description</Spalte>
                    </Member0>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>4</Anzahl>
                    <Member0>
                        <Spalte>Table01</Spalte>
                    </Member0>
                    <Member1>
                        <Spalte>Description</Spalte>
                    </Member1>
                    <Member2>
                        <Spalte>Deleted</Spalte>
                    </Member2>
                    <Member3>
                        <Spalte>Token</Spalte>
                    </Member3>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Table01</Spalte>
                    </Member0>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Richtung>ASC</Richtung>
                        <Spalte>Description</Spalte>
                        <Tabelle>Table01</Tabelle>
                    </Member0>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Description</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                    <Member1>
                        <Prefix> (</Prefix>
                        <Spalte>Token</Spalte>
                        <Suffix>)</Suffix>
                    </Member1>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Description</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                    <Member1>
                        <Prefix> (</Prefix>
                        <Spalte>Token</Spalte>
                        <Suffix>)</Suffix>
                    </Member1>
                </ToStringMembers>
            </Codegenerator>
            <ExternalTable>false</ExternalTable>
            <Farben>
                <Hintergrund>null</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Table01</Name>
            <Options>
                <Count>0</Count>
            </Options>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>5</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <AdditionalCreateConstraints></AdditionalCreateConstraints>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula>Description &amp; Deleted | Token &amp; Deleted</UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Table01</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Table04</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>DOWN</Direction0>
                        <Direction1>UP</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Spalte>Table04</Spalte>
                        <Tabelle>Table04</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>DOWN</Direction0>
                                <Direction1>UP</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>0</Anzahl>
                                </Points>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Deleted</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Description</Domain>
                    <Editordescriptor>
                        <Editormember>true</Editormember>
                        <LabelText>Bezeichnung</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>B</Mnemonic>
                        <Position>1</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldDescription</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier eine eindeutige,aussagekr&amp;auml;ftige Bezeichnung ein.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Description</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte3>
                <Spalte4>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Token</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText>K&amp;uuml;rzel</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>K</Mnemonic>
                        <Position>2</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldToken</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier ein eindeutiges, aussagekr&amp;auml;ftiges K&amp;uuml;rzel ein.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Token</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte4>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>50</X>
                    <Y>200</Y>
                </View0>
            </Views>
        </Tabelle0>
        <Tabelle1>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Spalte>Table01</Spalte>
                    </Member0>
                    <Member1>
                        <Spalte>Deleted</Spalte>
                    </Member1>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Table01</Spalte>
                    </Member0>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <ExternalTable>false</ExternalTable>
            <Farben>
                <Hintergrund>null</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>true</NMRelation>
            <Name>Table02</Name>
            <Options>
                <Count>0</Count>
            </Options>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>3</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <AdditionalCreateConstraints></AdditionalCreateConstraints>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula>Description &amp; Deleted | Token &amp; Deleted</UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Table01</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <Referenz>
                        <Direction0>LEFT</Direction0>
                        <Direction1>RIGHT</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Spalte>Table01</Spalte>
                        <Tabelle>Table01</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>LEFT</Direction0>
                                <Direction1>RIGHT</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>0</Anzahl>
                                </Points>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Table03</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <Referenz>
                        <Direction0>RIGHT</Direction0>
                        <Direction1>LEFT</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Spalte>Table03</Spalte>
                        <Tabelle>Table03</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>RIGHT</Direction0>
                                <Direction1>LEFT</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>0</Anzahl>
                                </Points>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Deleted</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte2>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>375</X>
                    <Y>200</Y>
                </View0>
            </Views>
        </Tabelle1>
        <Tabelle2>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Attribute>OPTIONAL</Attribute>
                        <Spalte>Description</Spalte>
                        <Tabelle>Table03</Tabelle>
                    </Member0>
                    <Member1>
                        <Attribute>OPTIONAL</Attribute>
                        <Spalte>Token</Spalte>
                        <Tabelle>Table03</Tabelle>
                    </Member1>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Description</Spalte>
                    </Member0>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>4</Anzahl>
                    <Member0>
                        <Spalte>Table03</Spalte>
                    </Member0>
                    <Member1>
                        <Spalte>Deleted</Spalte>
                    </Member1>
                    <Member2>
                        <Spalte>Description</Spalte>
                    </Member2>
                    <Member3>
                        <Spalte>Token</Spalte>
                    </Member3>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Table03</Spalte>
                    </Member0>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Richtung>ASC</Richtung>
                        <Spalte>Description</Spalte>
                        <Tabelle>Table03</Tabelle>
                    </Member0>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Description</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                    <Member1>
                        <Prefix> (</Prefix>
                        <Spalte>Token</Spalte>
                        <Suffix>)</Suffix>
                    </Member1>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Description</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                    <Member1>
                        <Prefix> (</Prefix>
                        <Spalte>Token</Spalte>
                        <Suffix>)</Suffix>
                    </Member1>
                </ToStringMembers>
            </Codegenerator>
            <ExternalTable>false</ExternalTable>
            <Farben>
                <Hintergrund>null</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Table03</Name>
            <Options>
                <Count>0</Count>
            </Options>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>4</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <AdditionalCreateConstraints></AdditionalCreateConstraints>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula>Description &amp; Deleted | Token &amp; Deleted</UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Table03</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Deleted</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Description</Domain>
                    <Editordescriptor>
                        <Editormember>true</Editormember>
                        <LabelText>Bezeichnung</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>B</Mnemonic>
                        <Position>1</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldDescription</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier eine eindeutige,aussagekr&amp;auml;ftige Bezeichnung ein.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Description</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Token</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText>K&amp;uuml;rzel</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>K</Mnemonic>
                        <Position>2</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldToken</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier ein eindeutiges, aussagekr&amp;auml;ftiges K&amp;uuml;rzel ein.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Token</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte3>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>650</X>
                    <Y>200</Y>
                </View0>
            </Views>
        </Tabelle2>
        <Tabelle3>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Attribute>OPTIONAL</Attribute>
                        <Spalte>Description</Spalte>
                        <Tabelle>Table04</Tabelle>
                    </Member0>
                    <Member1>
                        <Attribute>OPTIONAL</Attribute>
                        <Spalte>Token</Spalte>
                        <Tabelle>Table04</Tabelle>
                    </Member1>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Description</Spalte>
                    </Member0>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>4</Anzahl>
                    <Member0>
                        <Spalte>Table04</Spalte>
                    </Member0>
                    <Member1>
                        <Spalte>Description</Spalte>
                    </Member1>
                    <Member2>
                        <Spalte>Deleted</Spalte>
                    </Member2>
                    <Member3>
                        <Spalte>Token</Spalte>
                    </Member3>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Table04</Spalte>
                    </Member0>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Richtung>ASC</Richtung>
                        <Spalte>Description</Spalte>
                        <Tabelle>Table04</Tabelle>
                    </Member0>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Description</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                    <Member1>
                        <Prefix> (</Prefix>
                        <Spalte>Token</Spalte>
                        <Suffix>)</Suffix>
                    </Member1>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Description</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                    <Member1>
                        <Prefix> (</Prefix>
                        <Spalte>Token</Spalte>
                        <Suffix>)</Suffix>
                    </Member1>
                </ToStringMembers>
            </Codegenerator>
            <ExternalTable>false</ExternalTable>
            <Farben>
                <Hintergrund>null</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Table04</Name>
            <Options>
                <Count>0</Count>
            </Options>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>4</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <AdditionalCreateConstraints></AdditionalCreateConstraints>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula>Description &amp; Deleted | Token &amp; Deleted</UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Table04</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Deleted</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Description</Domain>
                    <Editordescriptor>
                        <Editormember>true</Editormember>
                        <LabelText>Bezeichnung</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>B</Mnemonic>
                        <Position>1</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldDescription</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier eine eindeutige,aussagekr&amp;auml;ftige Bezeichnung ein.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Description</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Token</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText>K&amp;uuml;rzel</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>K</Mnemonic>
                        <Position>2</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldToken</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier ein eindeutiges, aussagekr&amp;auml;ftiges K&amp;uuml;rzel ein.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Token</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte3>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>50</X>
                    <Y>400</Y>
                </View0>
            </Views>
        </Tabelle3>
    </Tabellen>
    <Views>
        <Anzahl>1</Anzahl>
        <View0>
            <Beschreibung>Diese Sicht beinhaltet alle Tabellen des Schemas</Beschreibung>
            <Name>Main</Name>
            <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
            <Tabelle0>Table01</Tabelle0>
            <Tabelle1>Table02</Tabelle1>
            <Tabelle2>Table03</Tabelle2>
            <Tabelle3>Table04</Tabelle3>
            <Tabellenanzahl>4</Tabellenanzahl>
            <TechnischeSpaltenVerstecken>false</TechnischeSpaltenVerstecken>
        </View0>
    </Views>
</Diagramm>
