<Diagramm>
    <Colors>
        <Anzahl>23</Anzahl>
        <Color0>
            <B>255</B>
            <G>0</G>
            <Name>blau</Name>
            <R>0</R>
        </Color0>
        <Color1>
            <B>221</B>
            <G>212</G>
            <Name>blaugrau</Name>
            <R>175</R>
        </Color1>
        <Color10>
            <B>192</B>
            <G>192</G>
            <Name>hellgrau</Name>
            <R>192</R>
        </Color10>
        <Color11>
            <B>255</B>
            <G>0</G>
            <Name>kamesinrot</Name>
            <R>255</R>
        </Color11>
        <Color12>
            <B>0</B>
            <G>200</G>
            <Name>orange</Name>
            <R>255</R>
        </Color12>
        <Color13>
            <B>255</B>
            <G>247</G>
            <Name>pastell-blau</Name>
            <R>211</R>
        </Color13>
        <Color14>
            <B>186</B>
            <G>245</G>
            <Name>pastell-gelb</Name>
            <R>255</R>
        </Color14>
        <Color15>
            <B>234</B>
            <G>255</G>
            <Name>pastell-gr&amp;uuml;n</Name>
            <R>211</R>
        </Color15>
        <Color16>
            <B>255</B>
            <G>211</G>
            <Name>pastell-lila</Name>
            <R>244</R>
        </Color16>
        <Color17>
            <B>191</B>
            <G>165</G>
            <Name>pastell-rot</Name>
            <R>244</R>
        </Color17>
        <Color18>
            <B>175</B>
            <G>175</G>
            <Name>pink</Name>
            <R>255</R>
        </Color18>
        <Color19>
            <B>0</B>
            <G>0</G>
            <Name>rot</Name>
            <R>255</R>
        </Color19>
        <Color2>
            <B>61</B>
            <G>125</G>
            <Name>braun</Name>
            <R>170</R>
        </Color2>
        <Color20>
            <B>0</B>
            <G>0</G>
            <Name>schwarz</Name>
            <R>0</R>
        </Color20>
        <Color21>
            <B>255</B>
            <G>255</G>
            <Name>t&amp;uuml;rkis</Name>
            <R>0</R>
        </Color21>
        <Color22>
            <B>255</B>
            <G>255</G>
            <Name>wei&amp;szlig;</Name>
            <R>255</R>
        </Color22>
        <Color3>
            <B>64</B>
            <G>64</G>
            <Name>dunkelgrau</Name>
            <R>64</R>
        </Color3>
        <Color4>
            <B>84</B>
            <G>132</G>
            <Name>dunkelgr&amp;uuml;n</Name>
            <R>94</R>
        </Color4>
        <Color5>
            <B>0</B>
            <G>255</G>
            <Name>gelb</Name>
            <R>255</R>
        </Color5>
        <Color6>
            <B>0</B>
            <G>225</G>
            <Name>goldgelb</Name>
            <R>255</R>
        </Color6>
        <Color7>
            <B>128</B>
            <G>128</G>
            <Name>grau</Name>
            <R>128</R>
        </Color7>
        <Color8>
            <B>0</B>
            <G>255</G>
            <Name>gr&amp;uuml;n</Name>
            <R>0</R>
        </Color8>
        <Color9>
            <B>255</B>
            <G>212</G>
            <Name>hellblau</Name>
            <R>191</R>
        </Color9>
    </Colors>
    <DataSource>
        <Update>
            <DBMode>MYSQL</DBMode>
            <DBName></DBName>
            <Description>no description</Description>
            <DomainFaehig>false</DomainFaehig>
            <Driver>org.gjt.mm.mysql.Driver</Driver>
            <FkNotNullBeachten>false</FkNotNullBeachten>
            <Name>unknown</Name>
            <ReferenzenSetzen>false</ReferenzenSetzen>
            <User></User>
        </Update>
    </DataSource>
    <DefaultComment>
        <Anzahl>0</Anzahl>
    </DefaultComment>
    <Domains>
        <Anzahl>6</Anzahl>
        <Domain0>
            <Datatype>4</Datatype>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Boolean</Name>
        </Domain0>
        <Domain1>
            <Datatype>12</Datatype>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>50</Length>
            <NKS>0</NKS>
            <Name>Description</Name>
        </Domain1>
        <Domain2>
            <Datatype>4</Datatype>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Ident</Name>
        </Domain2>
        <Domain3>
            <Datatype>12</Datatype>
            <Initialwert>NULL</Initialwert>
            <Kommentar>Ein Typ zur Darstellung lange Bezeichnungen.</Kommentar>
            <Length>255</Length>
            <NKS>0</NKS>
            <Name>LongDescription</Name>
        </Domain3>
        <Domain4>
            <Datatype>-1</Datatype>
            <Initialwert>NULL</Initialwert>
            <Kommentar>Diese Dom&amp;auml;ne ist f&amp;uuml;r Freitextfelder gedacht.</Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>LongText</Name>
        </Domain4>
        <Domain5>
            <Datatype>12</Datatype>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>10</Length>
            <NKS>0</NKS>
            <Name>Token</Name>
        </Domain5>
    </Domains>
    <Factories>
        <Object>archimedes.legacy.scheme.DefaultObjectFactory</Object>
    </Factories>
    <Pages>
        <PerColumn>1</PerColumn>
        <PerRow>1</PerRow>
    </Pages>
    <Parameter>
        <Applicationname>Archimedes</Applicationname>
        <AufgehobeneAusblenden>false</AufgehobeneAusblenden>
        <Autor>ollie</Autor>
        <Basepackagename>archimedes</Basepackagename>
        <CodeFactoryClassName></CodeFactoryClassName>
        <Codebasispfad>dev/codetmp/</Codebasispfad>
        <DBVersionDBVersionColumn></DBVersionDBVersionColumn>
        <DBVersionDescriptionColumn></DBVersionDescriptionColumn>
        <DBVersionTablename></DBVersionTablename>
        <Kommentar>:o)</Kommentar>
        <Name>Archimedes</Name>
        <PflichtfelderMarkieren>true</PflichtfelderMarkieren>
        <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
        <Schriftgroessen>
            <Tabelleninhalte>12</Tabelleninhalte>
            <Ueberschriften>24</Ueberschriften>
            <Untertitel>12</Untertitel>
        </Schriftgroessen>
        <Version>1</Version>
        <Versionsdatum>06.10.2007</Versionsdatum>
        <Versionskommentar>No Plan ;o)</Versionskommentar>
    </Parameter>
    <Stereotype>
        <Anzahl>1</Anzahl>
        <Stereotype0>
            <Kommentar>Diese Stereotype kennzeichnet eine Tabelle, deren Datens&amp;auml;tze nicht gel&amp;ouml;scht, sondern lediglich deaktiviert werden sollen.</Kommentar>
            <Name>Deaktivierbar</Name>
        </Stereotype0>
    </Stereotype>
    <Tabellen>
        <Anzahl>1</Anzahl>
        <Tabelle0>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Pattern</Spalte>
                        <Tabelle>DefaultComment</Tabelle>
                    </Member0>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Pattern</Spalte>
                    </Member0>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Spalte>Comment</Spalte>
                    </Member0>
                    <Member1>
                        <Spalte>Pattern</Spalte>
                    </Member1>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Pattern</Spalte>
                    </Member0>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Richtung>ASC</Richtung>
                        <Spalte>Pattern</Spalte>
                        <Tabelle>DefaultComment</Tabelle>
                    </Member0>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Pattern</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Prefix></Prefix>
                        <Spalte>Pattern</Spalte>
                        <Suffix></Suffix>
                    </Member0>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>blaugrau</Hintergrund>
                <Schrift>java.awt.Color[r=0,g=0,b=0]</Schrift>
            </Farben>
            <FirstGenerationDone>true</FirstGenerationDone>
            <InDevelopment>false</InDevelopment>
            <Kommentar>Diese Tabelle enth&amp;auml;lt Kommentare, die in der Beschreibung auf Tabellenspalten angewandt werden sollen, auf deren Namen das angegebene Muster pa&amp;szlig;t.</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>DefaultComment</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>2</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>true</ActiveInApplication>
                    <Codeverzeichnis>archimedes/scheme</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula>Pattern</UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>LongDescription</Domain>
                    <Editordescriptor>
                        <Editormember>true</Editormember>
                        <LabelText>Muster</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>M</Mnemonic>
                        <Position>2</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldPattern</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier das Muster an, mit Hilfe dessen die Spalten bestmmt werden, auf die der Kommentar angewandt werden soll.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <Kodiert>false</Kodiert>
                    <Kommentar>Das Muster, mit Hilfe dessen die Tabellenspalten bestimmt werden, auf die der Kommentar angewandt werden soll (falls sie keinen eigenen Kommentar haben).</Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <Name>Pattern</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>LongText</Domain>
                    <Editordescriptor>
                        <Editormember>true</Editormember>
                        <LabelText>Kommentar</LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic>K</Mnemonic>
                        <Position>2</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier>TextFieldComment</RessourceIdentifier>
                        <ToolTipText>Geben Sie hier den Kommentar an, der auf die zum Muster passenden Spalten angewandt werden soll.</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <Kodiert>false</Kodiert>
                    <Kommentar>Diese Spalte enth&amp;auml;lt den Kommentar, der auf Spalten angewandt werden soll, auf die das angegebene Muster (pattern) pa&amp;szlig;t, wenn diese keine eigene Beschreibung haben.</Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <Name>Comment</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                </Spalte1>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>100</X>
                    <Y>125</Y>
                </View0>
            </Views>
        </Tabelle0>
    </Tabellen>
    <Views>
        <Anzahl>1</Anzahl>
        <View0>
            <Beschreibung>Diese Sicht beinhaltet alle Tabellen des Schemas</Beschreibung>
            <Name>Main</Name>
            <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
            <Tabellenanzahl>0</Tabellenanzahl>
        </View0>
    </Views>
</Diagramm>
