<Diagramm>
    <Colors>
        <Anzahl>23</Anzahl>
        <Color0>
            <B>255</B>
            <G>0</G>
            <Name>blau</Name>
            <R>0</R>
        </Color0>
        <Color1>
            <B>221</B>
            <G>212</G>
            <Name>blaugrau</Name>
            <R>175</R>
        </Color1>
        <Color10>
            <B>192</B>
            <G>192</G>
            <Name>hellgrau</Name>
            <R>192</R>
        </Color10>
        <Color11>
            <B>255</B>
            <G>0</G>
            <Name>kamesinrot</Name>
            <R>255</R>
        </Color11>
        <Color12>
            <B>0</B>
            <G>200</G>
            <Name>orange</Name>
            <R>255</R>
        </Color12>
        <Color13>
            <B>255</B>
            <G>247</G>
            <Name>pastell-blau</Name>
            <R>211</R>
        </Color13>
        <Color14>
            <B>186</B>
            <G>245</G>
            <Name>pastell-gelb</Name>
            <R>255</R>
        </Color14>
        <Color15>
            <B>234</B>
            <G>255</G>
            <Name>pastell-gr&amp;uuml;n</Name>
            <R>211</R>
        </Color15>
        <Color16>
            <B>255</B>
            <G>211</G>
            <Name>pastell-lila</Name>
            <R>244</R>
        </Color16>
        <Color17>
            <B>191</B>
            <G>165</G>
            <Name>pastell-rot</Name>
            <R>244</R>
        </Color17>
        <Color18>
            <B>175</B>
            <G>175</G>
            <Name>pink</Name>
            <R>255</R>
        </Color18>
        <Color19>
            <B>0</B>
            <G>0</G>
            <Name>rot</Name>
            <R>255</R>
        </Color19>
        <Color2>
            <B>61</B>
            <G>125</G>
            <Name>braun</Name>
            <R>170</R>
        </Color2>
        <Color20>
            <B>0</B>
            <G>0</G>
            <Name>schwarz</Name>
            <R>0</R>
        </Color20>
        <Color21>
            <B>255</B>
            <G>255</G>
            <Name>t&amp;uuml;rkis</Name>
            <R>0</R>
        </Color21>
        <Color22>
            <B>255</B>
            <G>255</G>
            <Name>wei&amp;szlig;</Name>
            <R>255</R>
        </Color22>
        <Color3>
            <B>64</B>
            <G>64</G>
            <Name>dunkelgrau</Name>
            <R>64</R>
        </Color3>
        <Color4>
            <B>84</B>
            <G>132</G>
            <Name>dunkelgr&amp;uuml;n</Name>
            <R>94</R>
        </Color4>
        <Color5>
            <B>0</B>
            <G>255</G>
            <Name>gelb</Name>
            <R>255</R>
        </Color5>
        <Color6>
            <B>0</B>
            <G>225</G>
            <Name>goldgelb</Name>
            <R>255</R>
        </Color6>
        <Color7>
            <B>128</B>
            <G>128</G>
            <Name>grau</Name>
            <R>128</R>
        </Color7>
        <Color8>
            <B>0</B>
            <G>255</G>
            <Name>gr&amp;uuml;n</Name>
            <R>0</R>
        </Color8>
        <Color9>
            <B>255</B>
            <G>212</G>
            <Name>hellblau</Name>
            <R>191</R>
        </Color9>
    </Colors>
    <ComplexIndices>
        <IndexCount>0</IndexCount>
    </ComplexIndices>
    <DataSource>
        <Import>
            <DBName></DBName>
            <Description></Description>
            <Domains>false</Domains>
            <Driver></Driver>
            <Name></Name>
            <Referenzen>false</Referenzen>
            <User></User>
        </Import>
        <Update>
            <DBMode>MYSQL</DBMode>
            <DBName></DBName>
            <Description></Description>
            <DomainFaehig>false</DomainFaehig>
            <Driver></Driver>
            <FkNotNullBeachten>false</FkNotNullBeachten>
            <Name></Name>
            <ReferenzenSetzen>false</ReferenzenSetzen>
            <User></User>
        </Update>
    </DataSource>
    <DefaultComment>
        <Anzahl>0</Anzahl>
    </DefaultComment>
    <Domains>
        <Anzahl>1</Anzahl>
        <Domain0>
            <Datatype>4</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Ident</Name>
        </Domain0>
    </Domains>
    <Factories>
        <Object>archimedes.legacy.scheme.DefaultObjectFactory</Object>
    </Factories>
    <Pages>
        <PerColumn>5</PerColumn>
        <PerRow>10</PerRow>
    </Pages>
    <Parameter>
        <AdditionalSQLScriptListener></AdditionalSQLScriptListener>
        <Applicationname></Applicationname>
        <AufgehobeneAusblenden>false</AufgehobeneAusblenden>
        <Autor>ollie</Autor>
        <Basepackagename></Basepackagename>
        <CodeFactoryClassName></CodeFactoryClassName>
        <Codebasispfad>.\</Codebasispfad>
        <DBVersionDBVersionColumn></DBVersionDBVersionColumn>
        <DBVersionDescriptionColumn></DBVersionDescriptionColumn>
        <DBVersionTablename></DBVersionTablename>
        <History></History>
        <Kommentar>&amp;lt;null&amp;gt;</Kommentar>
        <Name>FK-TEST</Name>
        <PflichtfelderMarkieren>false</PflichtfelderMarkieren>
        <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
        <SchemaName></SchemaName>
        <Schriftgroessen>
            <Tabelleninhalte>12</Tabelleninhalte>
            <Ueberschriften>24</Ueberschriften>
            <Untertitel>12</Untertitel>
        </Schriftgroessen>
        <Scripte>
            <AfterWrite>&amp;lt;null&amp;gt;</AfterWrite>
        </Scripte>
        <TechnischeFelderAusgrauen>false</TechnischeFelderAusgrauen>
        <UdschebtiBaseClassName></UdschebtiBaseClassName>
        <Version>1</Version>
        <Versionsdatum>25.04.2013</Versionsdatum>
        <Versionskommentar>&amp;lt;null&amp;gt;</Versionskommentar>
    </Parameter>
    <Sequences>
        <Count>0</Count>
    </Sequences>
    <Stereotype>
        <Anzahl>0</Anzahl>
    </Stereotype>
    <Tabellen>
        <Anzahl>2</Anzahl>
        <Tabelle0>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>wei&amp;szlig;</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Tabelle1</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>1</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>75</X>
                    <Y>125</Y>
                </View0>
            </Views>
        </Tabelle0>
        <Tabelle1>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>wei&amp;szlig;</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Tabelle2</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>2</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Fk</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>LEFT</Direction0>
                        <Direction1>RIGHT</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Punkte>
                            <Anzahl>0</Anzahl>
                        </Punkte>
                        <Spalte>Id</Spalte>
                        <Tabelle>Tabelle1</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>LEFT</Direction0>
                                <Direction1>RIGHT</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Punkte>
                                    <Anzahl>0</Anzahl>
                                </Punkte>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>275</X>
                    <Y>125</Y>
                </View0>
            </Views>
        </Tabelle1>
    </Tabellen>
    <Views>
        <Anzahl>1</Anzahl>
        <View0>
            <Beschreibung>Diese Sicht beinhaltet alle Tabellen des Schemas</Beschreibung>
            <Name>Main</Name>
            <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
            <Tabelle0>Tabelle1</Tabelle0>
            <Tabelle1>Tabelle2</Tabelle1>
            <Tabellenanzahl>2</Tabellenanzahl>
            <TechnischeSpaltenVerstecken>false</TechnischeSpaltenVerstecken>
        </View0>
    </Views>
</Diagramm>
