<Diagramm>
    <AdditionalSQLCode>
        <SQLCode></SQLCode>
    </AdditionalSQLCode>
    <Colors>
        <Anzahl>23</Anzahl>
        <Color0>
            <B>255</B>
            <G>0</G>
            <Name>blau</Name>
            <R>0</R>
        </Color0>
        <Color1>
            <B>221</B>
            <G>212</G>
            <Name>blaugrau</Name>
            <R>175</R>
        </Color1>
        <Color10>
            <B>192</B>
            <G>192</G>
            <Name>hellgrau</Name>
            <R>192</R>
        </Color10>
        <Color11>
            <B>255</B>
            <G>0</G>
            <Name>kamesinrot</Name>
            <R>255</R>
        </Color11>
        <Color12>
            <B>0</B>
            <G>200</G>
            <Name>orange</Name>
            <R>255</R>
        </Color12>
        <Color13>
            <B>255</B>
            <G>247</G>
            <Name>pastell-blau</Name>
            <R>211</R>
        </Color13>
        <Color14>
            <B>186</B>
            <G>245</G>
            <Name>pastell-gelb</Name>
            <R>255</R>
        </Color14>
        <Color15>
            <B>234</B>
            <G>255</G>
            <Name>pastell-gr&amp;uuml;n</Name>
            <R>211</R>
        </Color15>
        <Color16>
            <B>255</B>
            <G>211</G>
            <Name>pastell-lila</Name>
            <R>244</R>
        </Color16>
        <Color17>
            <B>191</B>
            <G>165</G>
            <Name>pastell-rot</Name>
            <R>244</R>
        </Color17>
        <Color18>
            <B>175</B>
            <G>175</G>
            <Name>pink</Name>
            <R>255</R>
        </Color18>
        <Color19>
            <B>0</B>
            <G>0</G>
            <Name>rot</Name>
            <R>255</R>
        </Color19>
        <Color2>
            <B>61</B>
            <G>125</G>
            <Name>braun</Name>
            <R>170</R>
        </Color2>
        <Color20>
            <B>0</B>
            <G>0</G>
            <Name>schwarz</Name>
            <R>0</R>
        </Color20>
        <Color21>
            <B>255</B>
            <G>255</G>
            <Name>t&amp;uuml;rkis</Name>
            <R>0</R>
        </Color21>
        <Color22>
            <B>255</B>
            <G>255</G>
            <Name>wei&amp;szlig;</Name>
            <R>255</R>
        </Color22>
        <Color3>
            <B>64</B>
            <G>64</G>
            <Name>dunkelgrau</Name>
            <R>64</R>
        </Color3>
        <Color4>
            <B>84</B>
            <G>132</G>
            <Name>dunkelgr&amp;uuml;n</Name>
            <R>94</R>
        </Color4>
        <Color5>
            <B>0</B>
            <G>255</G>
            <Name>gelb</Name>
            <R>255</R>
        </Color5>
        <Color6>
            <B>0</B>
            <G>225</G>
            <Name>goldgelb</Name>
            <R>255</R>
        </Color6>
        <Color7>
            <B>128</B>
            <G>128</G>
            <Name>grau</Name>
            <R>128</R>
        </Color7>
        <Color8>
            <B>0</B>
            <G>255</G>
            <Name>gr&amp;uuml;n</Name>
            <R>0</R>
        </Color8>
        <Color9>
            <B>255</B>
            <G>212</G>
            <Name>hellblau</Name>
            <R>191</R>
        </Color9>
    </Colors>
    <ComplexIndices>
        <IndexCount>0</IndexCount>
    </ComplexIndices>
    <DataSource>
        <Import>
            <DBName></DBName>
            <Description></Description>
            <Domains>false</Domains>
            <Driver></Driver>
            <Name></Name>
            <Referenzen>false</Referenzen>
            <User></User>
        </Import>
        <Update>
            <DBMode>POSTGRESQL</DBMode>
            <DBName>jdbc:postgresql://mykene/TEST_OLI_ISIS</DBName>
            <Description></Description>
            <DomainFaehig>false</DomainFaehig>
            <Driver>org.postgresql.Driver</Driver>
            <FkNotNullBeachten>false</FkNotNullBeachten>
            <Name></Name>
            <ReferenzenSetzen>false</ReferenzenSetzen>
            <User>op1</User>
        </Update>
    </DataSource>
    <DefaultComment>
        <Anzahl>0</Anzahl>
    </DefaultComment>
    <Domains>
        <Anzahl>5</Anzahl>
        <Domain0>
            <Datatype>4</Datatype>
            <History></History>
            <Initialwert>0</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Boolean</Name>
        </Domain0>
        <Domain1>
            <Datatype>4</Datatype>
            <History></History>
            <Initialwert>0</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Ident</Name>
        </Domain1>
        <Domain2>
            <Datatype>4</Datatype>
            <History></History>
            <Initialwert>42</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Integer</Name>
        </Domain2>
        <Domain3>
            <Datatype>-5</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>PTimestamp</Name>
        </Domain3>
        <Domain4>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>20</Length>
            <NKS>0</NKS>
            <Name>Token</Name>
        </Domain4>
    </Domains>
    <Factories>
        <Object>archimedes.legacy.scheme.DefaultObjectFactory</Object>
    </Factories>
    <Pages>
        <PerColumn>5</PerColumn>
        <PerRow>10</PerRow>
    </Pages>
    <Parameter>
        <AdditionalSQLScriptListener></AdditionalSQLScriptListener>
        <Applicationname></Applicationname>
        <AufgehobeneAusblenden>false</AufgehobeneAusblenden>
        <Autor>E.Presley</Autor>
        <Basepackagename>com.moppelsoft.project</Basepackagename>
        <CodeFactoryClassName></CodeFactoryClassName>
        <Codebasispfad>.\</Codebasispfad>
        <DBVersionDBVersionColumn></DBVersionDBVersionColumn>
        <DBVersionDescriptionColumn></DBVersionDescriptionColumn>
        <DBVersionTablename></DBVersionTablename>
        <History></History>
        <Kommentar>&amp;lt;null&amp;gt;</Kommentar>
        <Name>TestDiagram (FOR SCHEMA TESTS)</Name>
        <PflichtfelderMarkieren>false</PflichtfelderMarkieren>
        <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
        <SchemaName>TestSchema</SchemaName>
        <Schriftgroessen>
            <Tabelleninhalte>12</Tabelleninhalte>
            <Ueberschriften>24</Ueberschriften>
            <Untertitel>12</Untertitel>
        </Schriftgroessen>
        <Scripte>
            <AfterWrite>&amp;lt;null&amp;gt;</AfterWrite>
        </Scripte>
        <TechnischeFelderAusgrauen>true</TechnischeFelderAusgrauen>
        <UdschebtiBaseClassName></UdschebtiBaseClassName>
        <Version>1</Version>
        <Versionsdatum>07.01.2011</Versionsdatum>
        <Versionskommentar>&amp;lt;null&amp;gt;</Versionskommentar>
    </Parameter>
    <Sequences>
        <Count>0</Count>
    </Sequences>
    <Stereotype>
        <Anzahl>4</Anzahl>
        <Stereotype0>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>-/-</Kommentar>
            <Name>A</Name>
        </Stereotype0>
        <Stereotype1>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>-/-</Kommentar>
            <Name>B</Name>
        </Stereotype1>
        <Stereotype2>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>-/-</Kommentar>
            <Name>C</Name>
        </Stereotype2>
        <Stereotype3>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History></History>
            <Kommentar>-/-</Kommentar>
            <Name>D</Name>
        </Stereotype3>
    </Stereotype>
    <Tabellen>
        <Anzahl>5</Anzahl>
        <Tabelle0>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>wei&amp;szlig;</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>TableClass</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>3</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Active</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Integer</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Counter</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Reference</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>RIGHT</Direction0>
                        <Direction1>LEFT</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Spalte>Id</Spalte>
                        <Tabelle>AnotherTableClass</Tabelle>
                        <Views>
                            <Anzahl>2</Anzahl>
                            <View0>
                                <Direction0>LEFT</Direction0>
                                <Direction1>UP</Direction1>
                                <Name>Subview</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>2</Anzahl>
                                    <Point1>
                                        <X>475</X>
                                        <Y>100</Y>
                                    </Point1>
                                    <Point2>
                                        <X>425</X>
                                        <Y>150</Y>
                                    </Point2>
                                </Points>
                            </View0>
                            <View1>
                                <Direction0>RIGHT</Direction0>
                                <Direction1>LEFT</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>0</Anzahl>
                                </Points>
                            </View1>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
            </Spalten>
            <Stereotype>
                <Anzahl>2</Anzahl>
            </Stereotype>
            <Stereotype0>A</Stereotype0>
            <Stereotype1>B</Stereotype1>
            <Views>
                <Anzahl>2</Anzahl>
                <View0>
                    <Name>Subview</Name>
                    <X>725</X>
                    <Y>75</Y>
                </View0>
                <View1>
                    <Name>Main</Name>
                    <X>125</X>
                    <Y>125</Y>
                </View1>
            </Views>
        </Tabelle0>
        <Tabelle1>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>wei&amp;szlig;</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>AnotherTableClass</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>4</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>PTimestamp</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Timestamp</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Token</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue>""</IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Token</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Reference</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>RIGHT</Direction0>
                        <Direction1>UP</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>250</Offset1>
                        <Spalte>Id</Spalte>
                        <Tabelle>ReferencedTableClass</Tabelle>
                        <Views>
                            <Anzahl>2</Anzahl>
                            <View0>
                                <Direction0>RIGHT</Direction0>
                                <Direction1>UP</Direction1>
                                <Name>Subview</Name>
                                <Offset0>25</Offset0>
                                <Offset1>31</Offset1>
                                <Points>
                                    <Anzahl>2</Anzahl>
                                    <Point1>
                                        <X>675</X>
                                        <Y>350</Y>
                                    </Point1>
                                    <Point2>
                                        <X>700</X>
                                        <Y>375</Y>
                                    </Point2>
                                </Points>
                            </View0>
                            <View1>
                                <Direction0>RIGHT</Direction0>
                                <Direction1>UP</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>250</Offset1>
                                <Points>
                                    <Anzahl>2</Anzahl>
                                    <Point1>
                                        <X>800</X>
                                        <Y>150</Y>
                                    </Point1>
                                    <Point2>
                                        <X>850</X>
                                        <Y>200</Y>
                                    </Point2>
                                </Points>
                            </View1>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte3>
            </Spalten>
            <Stereotype>
                <Anzahl>1</Anzahl>
            </Stereotype>
            <Stereotype0>A</Stereotype0>
            <Views>
                <Anzahl>2</Anzahl>
                <View0>
                    <Name>Subview</Name>
                    <X>400</X>
                    <Y>325</Y>
                </View0>
                <View1>
                    <Name>Main</Name>
                    <X>400</X>
                    <Y>125</Y>
                </View1>
            </Views>
        </Tabelle1>
        <Tabelle2>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>wei&amp;szlig;</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>UpdateMethodTableClass</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>6</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue>1</IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Active</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Integer</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Counter</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Deleted</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>true</TechnicalField>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>PTimestamp</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Timestamp</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte3>
                <Spalte4>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Token</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Token</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte4>
                <Spalte5>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Reference</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>RIGHT</Direction0>
                        <Direction1>DOWN</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Spalte>Id</Spalte>
                        <Tabelle>AnotherTableClass</Tabelle>
                        <Views>
                            <Anzahl>2</Anzahl>
                            <View0>
                                <Direction0>UP</Direction0>
                                <Direction1>LEFT</Direction1>
                                <Name>Subview</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>3</Anzahl>
                                    <Point1>
                                        <X>150</X>
                                        <Y>425</Y>
                                    </Point1>
                                    <Point2>
                                        <X>175</X>
                                        <Y>375</Y>
                                    </Point2>
                                    <Point3>
                                        <X>225</X>
                                        <Y>350</Y>
                                    </Point3>
                                </Points>
                            </View0>
                            <View1>
                                <Direction0>RIGHT</Direction0>
                                <Direction1>DOWN</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>0</Anzahl>
                                </Points>
                            </View1>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte5>
            </Spalten>
            <Stereotype>
                <Anzahl>1</Anzahl>
            </Stereotype>
            <Stereotype0>C</Stereotype0>
            <Views>
                <Anzahl>2</Anzahl>
                <View0>
                    <Name>Subview</Name>
                    <X>125</X>
                    <Y>575</Y>
                </View0>
                <View1>
                    <Name>Main</Name>
                    <X>125</X>
                    <Y>350</Y>
                </View1>
            </Views>
        </Tabelle2>
        <Tabelle3>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>1</Anzahl>
                    <NReferenz0>
                        <Alterable>true</Alterable>
                        <Extensible>true</Extensible>
                        <Id>1</Id>
                        <Panel>1</Panel>
                        <PanelType>ausw&auml;hlbar</PanelType>
                        <PermitCreate>true</PermitCreate>
                        <Spalte>Reference</Spalte>
                        <Tabelle>AnotherTableClass</Tabelle>
                    </NReferenz0>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>rot</Hintergrund>
                <Schrift>dunkelgrau</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>true</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>true</NMRelation>
            <Name>ReferencedTableClass</Name>
            <Panels>
                <Anzahl>2</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
                <Panel1>
                    <PanelClass>PanelClass</PanelClass>
                    <PanelNumber>1</PanelNumber>
                    <TabMnemonic>N</TabMnemonic>
                    <TabTitle>2. Noch ein Panel</TabTitle>
                    <TabToolTipText>Und noch ein Panel</TabToolTipText>
                </Panel1>
            </Panels>
            <Spalten>
                <Anzahl>3</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Token</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Token</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>true</AlterInBatch>
                    <Aufgehoben>true</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>true</Disabled>
                    <Domain>PTimestamp</Domain>
                    <Editordescriptor>
                        <Editormember>true</Editormember>
                        <LabelText>Dingsbums</LabelText>
                        <MaxCharacters>4711</MaxCharacters>
                        <Mnemonic>D</Mnemonic>
                        <Position>42</Position>
                        <ReferenceWeight>massiv</ReferenceWeight>
                        <RessourceIdentifier>DingsbumsEingabefeld</RessourceIdentifier>
                        <ToolTipText>la la la bla bla bla</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>true</Global>
                    <GlobalId>true</GlobalId>
                    <HideReference>false</HideReference>
                    <History>;op</History>
                    <IndexSearchMember>true</IndexSearchMember>
                    <Indexed>true</Indexed>
                    <IndividualDefaultValue>20130403084700</IndividualDefaultValue>
                    <Kodiert>true</Kodiert>
                    <Kommentar>:o)</Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>true</LastModificationField>
                    <ListItemField>true</ListItemField>
                    <Name>NEU</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>1</PanelNumber>
                    <Parameter>laber</Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <Referenz>
                        <Direction0>UP</Direction0>
                        <Direction1>RIGHT</Direction1>
                        <Offset0>75</Offset0>
                        <Offset1>50</Offset1>
                        <Spalte>Id</Spalte>
                        <Tabelle>AnotherTableClass</Tabelle>
                        <Views>
                            <Anzahl>2</Anzahl>
                            <View0>
                                <Direction0>LEFT</Direction0>
                                <Direction1>DOWN</Direction1>
                                <Name>Subview</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>2</Anzahl>
                                    <Point1>
                                        <X>475</X>
                                        <Y>575</Y>
                                    </Point1>
                                    <Point2>
                                        <X>425</X>
                                        <Y>525</Y>
                                    </Point2>
                                </Points>
                            </View0>
                            <View1>
                                <Direction0>UP</Direction0>
                                <Direction1>RIGHT</Direction1>
                                <Name>Main</Name>
                                <Offset0>75</Offset0>
                                <Offset1>50</Offset1>
                                <Points>
                                    <Anzahl>1</Anzahl>
                                    <Point1>
                                        <X>675</X>
                                        <Y>175</Y>
                                    </Point1>
                                </Points>
                            </View1>
                        </Views>
                    </Referenz>
                    <RemovedStateField>true</RemovedStateField>
                    <TechnicalField>true</TechnicalField>
                    <Unique>true</Unique>
                </Spalte2>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>2</Anzahl>
                <View0>
                    <Name>Subview</Name>
                    <X>675</X>
                    <Y>550</Y>
                </View0>
                <View1>
                    <Name>Main</Name>
                    <X>600</X>
                    <Y>400</Y>
                </View1>
            </Views>
        </Tabelle3>
        <Tabelle4>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <Farben>
                <Hintergrund>wei&amp;szlig;</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History></History>
            <InDevelopment>true</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Tabelle5</Name>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>2</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Integer</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>neu</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>UP</Direction0>
                        <Direction1>DOWN</Direction1>
                        <Offset0>50</Offset0>
                        <Offset1>100</Offset1>
                        <Spalte>Id</Spalte>
                        <Tabelle>AnotherTableClass</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>UP</Direction0>
                                <Direction1>DOWN</Direction1>
                                <Name>Main</Name>
                                <Offset0>50</Offset0>
                                <Offset1>100</Offset1>
                                <Points>
                                    <Anzahl>4</Anzahl>
                                    <Point1>
                                        <X>500</X>
                                        <Y>600</Y>
                                    </Point1>
                                    <Point2>
                                        <X>450</X>
                                        <Y>550</Y>
                                    </Point2>
                                    <Point3>
                                        <X>450</X>
                                        <Y>350</Y>
                                    </Point3>
                                    <Point4>
                                        <X>500</X>
                                        <Y>300</Y>
                                    </Point4>
                                </Points>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History></History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>neu1</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>UP</Direction0>
                        <Direction1>DOWN</Direction1>
                        <Offset0>100</Offset0>
                        <Offset1>150</Offset1>
                        <Spalte>Id</Spalte>
                        <Tabelle>AnotherTableClass</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>UP</Direction0>
                                <Direction1>DOWN</Direction1>
                                <Name>Main</Name>
                                <Offset0>100</Offset0>
                                <Offset1>150</Offset1>
                                <Points>
                                    <Anzahl>0</Anzahl>
                                </Points>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <TechnicalField>false</TechnicalField>
                    <Unique>false</Unique>
                </Spalte1>
            </Spalten>
            <Stereotype>
                <Anzahl>0</Anzahl>
            </Stereotype>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>450</X>
                    <Y>650</Y>
                </View0>
            </Views>
        </Tabelle4>
    </Tabellen>
    <Views>
        <Anzahl>2</Anzahl>
        <View0>
            <Beschreibung>Diese Sicht beinhaltet alle Tabellen des Schemas</Beschreibung>
            <Name>Main</Name>
            <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
            <Tabelle0>TableClass</Tabelle0>
            <Tabelle1>AnotherTableClass</Tabelle1>
            <Tabelle2>UpdateMethodTableClass</Tabelle2>
            <Tabelle3>ReferencedTableClass</Tabelle3>
            <Tabelle4>Tabelle5</Tabelle4>
            <Tabellenanzahl>5</Tabellenanzahl>
            <TechnischeSpaltenVerstecken>false</TechnischeSpaltenVerstecken>
        </View0>
        <View1>
            <Beschreibung>-/-</Beschreibung>
            <Name>Subview</Name>
            <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
            <Tabelle0>TableClass</Tabelle0>
            <Tabelle1>AnotherTableClass</Tabelle1>
            <Tabelle2>UpdateMethodTableClass</Tabelle2>
            <Tabelle3>ReferencedTableClass</Tabelle3>
            <Tabellenanzahl>4</Tabellenanzahl>
            <TechnischeSpaltenVerstecken>true</TechnischeSpaltenVerstecken>
        </View1>
    </Views>
</Diagramm>
