<Diagramm>
    <AdditionalSQLCode>
        <SQLCode>
            <AdditionalSQLCodePostChanging>Script C</AdditionalSQLCodePostChanging>
            <AdditionalSQLCodePostReducing>Script D</AdditionalSQLCodePostReducing>
            <AdditionalSQLCodePreChanging>Script B</AdditionalSQLCodePreChanging>
            <AdditionalSQLCodePreExtending>Script A</AdditionalSQLCodePreExtending>
        </SQLCode>
    </AdditionalSQLCode>
    <Colors>
        <Anzahl>23</Anzahl>
        <Color0>
            <B>255</B>
            <G>0</G>
            <Name>blau</Name>
            <R>0</R>
        </Color0>
        <Color1>
            <B>221</B>
            <G>212</G>
            <Name>blaugrau</Name>
            <R>175</R>
        </Color1>
        <Color10>
            <B>192</B>
            <G>192</G>
            <Name>hellgrau</Name>
            <R>192</R>
        </Color10>
        <Color11>
            <B>255</B>
            <G>0</G>
            <Name>kamesinrot</Name>
            <R>255</R>
        </Color11>
        <Color12>
            <B>0</B>
            <G>200</G>
            <Name>orange</Name>
            <R>255</R>
        </Color12>
        <Color13>
            <B>255</B>
            <G>247</G>
            <Name>pastell-blau</Name>
            <R>211</R>
        </Color13>
        <Color14>
            <B>186</B>
            <G>245</G>
            <Name>pastell-gelb</Name>
            <R>255</R>
        </Color14>
        <Color15>
            <B>234</B>
            <G>255</G>
            <Name>pastell-gr&amp;uuml;n</Name>
            <R>211</R>
        </Color15>
        <Color16>
            <B>255</B>
            <G>211</G>
            <Name>pastell-lila</Name>
            <R>244</R>
        </Color16>
        <Color17>
            <B>191</B>
            <G>165</G>
            <Name>pastell-rot</Name>
            <R>244</R>
        </Color17>
        <Color18>
            <B>175</B>
            <G>175</G>
            <Name>pink</Name>
            <R>255</R>
        </Color18>
        <Color19>
            <B>0</B>
            <G>0</G>
            <Name>rot</Name>
            <R>255</R>
        </Color19>
        <Color2>
            <B>61</B>
            <G>125</G>
            <Name>braun</Name>
            <R>170</R>
        </Color2>
        <Color20>
            <B>0</B>
            <G>0</G>
            <Name>schwarz</Name>
            <R>0</R>
        </Color20>
        <Color21>
            <B>255</B>
            <G>255</G>
            <Name>t&amp;uuml;rkis</Name>
            <R>0</R>
        </Color21>
        <Color22>
            <B>255</B>
            <G>255</G>
            <Name>wei&amp;szlig;</Name>
            <R>255</R>
        </Color22>
        <Color3>
            <B>64</B>
            <G>64</G>
            <Name>dunkelgrau</Name>
            <R>64</R>
        </Color3>
        <Color4>
            <B>84</B>
            <G>132</G>
            <Name>dunkelgr&amp;uuml;n</Name>
            <R>94</R>
        </Color4>
        <Color5>
            <B>0</B>
            <G>255</G>
            <Name>gelb</Name>
            <R>255</R>
        </Color5>
        <Color6>
            <B>0</B>
            <G>225</G>
            <Name>goldgelb</Name>
            <R>255</R>
        </Color6>
        <Color7>
            <B>128</B>
            <G>128</G>
            <Name>grau</Name>
            <R>128</R>
        </Color7>
        <Color8>
            <B>0</B>
            <G>255</G>
            <Name>gr&amp;uuml;n</Name>
            <R>0</R>
        </Color8>
        <Color9>
            <B>255</B>
            <G>212</G>
            <Name>hellblau</Name>
            <R>191</R>
        </Color9>
    </Colors>
    <ComplexIndices>
        <Index0>
            <Column0>
                <Name>Building</Name>
            </Column0>
            <Column1>
                <Name>RoomNumber</Name>
            </Column1>
            <ColumnCount>2</ColumnCount>
            <Name>Room_Building_RoomNumber</Name>
            <Table>
                <Name>Room</Name>
            </Table>
        </Index0>
        <IndexCount>1</IndexCount>
    </ComplexIndices>
    <DataSource>
        <Import>
            <DBName>B</DBName>
            <Description></Description>
            <Domains>true</Domains>
            <Driver>A</Driver>
            <Name></Name>
            <Referenzen>true</Referenzen>
            <User>C</User>
        </Import>
    </DataSource>
    <DatabaseConnections>
        <Count>1</Count>
        <DatabaseConnection0>
            <DBExecMode>HSQL</DBExecMode>
            <Driver>org.hsqldb.jdbcDriver</Driver>
            <Name>HypersonicSQL</Name>
            <Quote>"</Quote>
            <SetDomains>true</SetDomains>
            <SetNotNull>true</SetNotNull>
            <SetReferences>true</SetReferences>
            <URL>jdbc:hsqldb:DATABASE_NAME</URL>
            <UserName>op1</UserName>
        </DatabaseConnection0>
    </DatabaseConnections>
    <DefaultComment>
        <Anzahl>0</Anzahl>
    </DefaultComment>
    <Domains>
        <Anzahl>4</Anzahl>
        <Domain0>
            <Datatype>-7</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Boolean</Name>
            <Parameters></Parameters>
        </Domain0>
        <Domain1>
            <Datatype>12</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>50</Length>
            <NKS>0</NKS>
            <Name>Description</Name>
            <Parameters></Parameters>
        </Domain1>
        <Domain2>
            <Datatype>4</Datatype>
            <History>Nochmal bla</History>
            <Initialwert>4711</Initialwert>
            <Kommentar>Bla</Kommentar>
            <Length>1</Length>
            <NKS>2</NKS>
            <Name>Dummy</Name>
            <Parameters>DOOF</Parameters>
        </Domain2>
        <Domain3>
            <Datatype>-5</Datatype>
            <History></History>
            <Initialwert>NULL</Initialwert>
            <Kommentar></Kommentar>
            <Length>0</Length>
            <NKS>0</NKS>
            <Name>Ident</Name>
            <Parameters></Parameters>
        </Domain3>
    </Domains>
    <Factories>
        <Object>archimedes.legacy.scheme.DefaultObjectFactory</Object>
    </Factories>
    <Pages>
        <PerColumn>5</PerColumn>
        <PerRow>10</PerRow>
    </Pages>
    <Parameter>
        <AdditionalSQLScriptListener>fan.tasy.Listener</AdditionalSQLScriptListener>
        <Applicationname>THE-APP</Applicationname>
        <AufgehobeneAusblenden>true</AufgehobeneAusblenden>
        <Autor>OLI</Autor>
        <Basepackagename>app.base</Basepackagename>
        <CodeFactoryClassName>fan.tasy.CodeGenerator</CodeFactoryClassName>
        <Codebasispfad>.\</Codebasispfad>
        <DBVersionDBVersionColumn>Version</DBVersionDBVersionColumn>
        <DBVersionDescriptionColumn>Description</DBVersionDescriptionColumn>
        <DBVersionTablename>Versions</DBVersionTablename>
        <History>Done something on last Friday.</History>
        <Kommentar>Bla bla$BR$bla$BR$laber</Kommentar>
        <Name>TST</Name>
        <Optionen>
            <Anzahl>2</Anzahl>
            <Option0>
                <Name>OPTION_1</Name>
                <Parameter>one</Parameter>
            </Option0>
            <Option1>
                <Name>OPTION_2</Name>
                <Parameter>Two</Parameter>
            </Option1>
        </Optionen>
        <PflichtfelderMarkieren>true</PflichtfelderMarkieren>
        <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
        <RelationColorExternalTables>hellgrau</RelationColorExternalTables>
        <RelationColorRegular>schwarz</RelationColorRegular>
        <SchemaName>SCHEME</SchemaName>
        <Schriftgroessen>
            <Tabelleninhalte>14</Tabelleninhalte>
            <Ueberschriften>28</Ueberschriften>
            <Untertitel>14</Untertitel>
        </Schriftgroessen>
        <Scripte>
            <AfterWrite>&amp;lt;null&amp;gt;</AfterWrite>
        </Scripte>
        <TechnischeFelderAusgrauen>true</TechnischeFelderAusgrauen>
        <TransienteFelderAusgrauen>true</TransienteFelderAusgrauen>
        <UdschebtiBaseClassName>NoneUschepti</UdschebtiBaseClassName>
        <Version>3</Version>
        <Versionsdatum>11.03.2016</Versionsdatum>
        <Versionskommentar>4711</Versionskommentar>
    </Parameter>
    <Sequences>
        <Count>2</Count>
        <Sequence0>
            <Comment></Comment>
            <History></History>
            <Increment>25</Increment>
            <Name>BuildingSeq</Name>
            <StartValue>50</StartValue>
        </Sequence0>
        <Sequence1>
            <Comment>bla, bla$BR$s&amp;uuml;lz</Comment>
            <History>1. added$BR$2. changed</History>
            <Increment>50</Increment>
            <Name>RoomSeq</Name>
            <StartValue>100</StartValue>
        </Sequence1>
    </Sequences>
    <Stereotype>
        <Anzahl>3</Anzahl>
        <Stereotype0>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History>B</History>
            <Kommentar>A</Kommentar>
            <Name>Anchor</Name>
        </Stereotype0>
        <Stereotype1>
            <DoNotPrint>true</DoNotPrint>
            <HideTable>true</HideTable>
            <History>Y</History>
            <Kommentar>X</Kommentar>
            <Name>Dummy</Name>
        </Stereotype1>
        <Stereotype2>
            <DoNotPrint>false</DoNotPrint>
            <HideTable>false</HideTable>
            <History>D</History>
            <Kommentar>C</Kommentar>
            <Name>ListObject</Name>
        </Stereotype2>
    </Stereotype>
    <Tabellen>
        <Anzahl>2</Anzahl>
        <Tabelle0>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Attribute>OPTIONAL</Attribute>
                        <Spalte>Id</Spalte>
                        <Tabelle>Building</Tabelle>
                    </Member0>
                    <Member1>
                        <Attribute>IMPORTANT</Attribute>
                        <Spalte>Name</Spalte>
                        <Tabelle>Building</Tabelle>
                    </Member1>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Spalte>Name</Spalte>
                    </Member0>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Spalte>Id</Spalte>
                    </Member0>
                    <Member1>
                        <Spalte>Name</Spalte>
                    </Member1>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Spalte>Name</Spalte>
                    </Member0>
                    <Member1>
                        <Spalte>Id</Spalte>
                    </Member1>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>1</Anzahl>
                    <NReferenz0>
                        <Alterable>true</Alterable>
                        <DeleteConfirmationRequired>true</DeleteConfirmationRequired>
                        <Extensible>true</Extensible>
                        <Id>1</Id>
                        <Panel>1</Panel>
                        <PanelType>standard</PanelType>
                        <PermitCreate>true</PermitCreate>
                        <Spalte>Building</Spalte>
                        <Tabelle>Room</Tabelle>
                    </NReferenz0>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Richtung>ASC</Richtung>
                        <Spalte>Name</Spalte>
                        <Tabelle>Building</Tabelle>
                    </Member0>
                    <Member1>
                        <Richtung>DESC</Richtung>
                        <Spalte>Id</Spalte>
                        <Tabelle>Building</Tabelle>
                    </Member1>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>1</Anzahl>
                    <Member0>
                        <Prefix>&lt;</Prefix>
                        <Spalte>Name</Spalte>
                        <Suffix>&gt;</Suffix>
                    </Member0>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>2</Anzahl>
                    <Member0>
                        <Prefix>Id=</Prefix>
                        <Spalte>Id</Spalte>
                        <Suffix>, </Suffix>
                    </Member0>
                    <Member1>
                        <Prefix>Name=</Prefix>
                        <Spalte>Name</Spalte>
                        <Suffix></Suffix>
                    </Member1>
                </ToStringMembers>
            </Codegenerator>
            <ExternalTable>false</ExternalTable>
            <Farben>
                <Hintergrund>goldgelb</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>true</FirstGenerationDone>
            <History>@changed OLI - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar>Comment</Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Building</Name>
            <Options>
                <Count>3</Count>
                <Option0>
                    <Name>OPT1</Name>
                    <Parameter>ena</Parameter>
                </Option0>
                <Option1>
                    <Name>OPT2</Name>
                    <Parameter>dyo</Parameter>
                </Option1>
                <Option2>
                    <Name>OPT3</Name>
                    <Parameter>tres</Parameter>
                </Option2>
            </Options>
            <Panels>
                <Anzahl>2</Anzahl>
                <Panel0>
                    <PanelClass>FORM</PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>data</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
                <Panel1>
                    <PanelClass>LIST</PanelClass>
                    <PanelNumber>1</PanelNumber>
                    <TabMnemonic>A</TabMnemonic>
                    <TabTitle>rooms</TabTitle>
                    <TabToolTipText>The rooms</TabToolTipText>
                </Panel1>
            </Panels>
            <Spalten>
                <Anzahl>2</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>true</ActiveInApplication>
                    <AdditionalCreateConstraints>Constraint</AdditionalCreateConstraints>
                    <Codegeneratoroptionen>OPT</Codegeneratoroptionen>
                    <Codeverzeichnis>pack</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>true</Inherited>
                    <Kontextname>Context</Kontextname>
                    <UniqueFormula>Id &amp; Name</UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>true</AlterInBatch>
                    <Aufgehoben>true</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>true</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>true</Editormember>
                        <LabelText>Id</LabelText>
                        <MaxCharacters>42</MaxCharacters>
                        <Mnemonic>I</Mnemonic>
                        <Position>1</Position>
                        <ReferenceWeight>wenige</ReferenceWeight>
                        <RessourceIdentifier>A</RessourceIdentifier>
                        <ToolTipText>The id</ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>true</Global>
                    <GlobalId>true</GlobalId>
                    <HideReference>true</HideReference>
                    <History>@changed OLI - Added.</History>
                    <IndexSearchMember>true</IndexSearchMember>
                    <Indexed>true</Indexed>
                    <IndividualDefaultValue>4711</IndividualDefaultValue>
                    <Kodiert>true</Kodiert>
                    <Kommentar>bla bla$BR$laber$BR$s&amp;uuml;lz</Kommentar>
                    <Konsistenz>
                        <Writeablemember>true</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>true</LastModificationField>
                    <ListItemField>true</ListItemField>
                    <Name>Id</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter>B</Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>true</RemovedStateField>
                    <SequenceForKeyGeneration>BuildingSeq</SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>true</SuppressForeignKeyConstraints>
                    <TechnicalField>true</TechnicalField>
                    <Transient>true</Transient>
                    <Unique>true</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Description</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Name</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte1>
            </Spalten>
            <Stereotype>
                <Anzahl>1</Anzahl>
            </Stereotype>
            <Stereotype0>Anchor</Stereotype0>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>400</X>
                    <Y>125</Y>
                </View0>
            </Views>
        </Tabelle0>
        <Tabelle1>
            <Aufgehoben>false</Aufgehoben>
            <Codegenerator>
                <AuswahlMembers>
                    <Anzahl>0</Anzahl>
                </AuswahlMembers>
                <CompareMembers>
                    <Anzahl>0</Anzahl>
                </CompareMembers>
                <Equalsmembers>
                    <Anzahl>0</Anzahl>
                </Equalsmembers>
                <HashCodeMembers>
                    <Anzahl>0</Anzahl>
                </HashCodeMembers>
                <NReferenzen>
                    <Anzahl>0</Anzahl>
                </NReferenzen>
                <OrderMembers>
                    <Anzahl>0</Anzahl>
                </OrderMembers>
                <ToComboStringMembers>
                    <Anzahl>0</Anzahl>
                </ToComboStringMembers>
                <ToStringMembers>
                    <Anzahl>0</Anzahl>
                </ToStringMembers>
            </Codegenerator>
            <ExternalTable>false</ExternalTable>
            <Farben>
                <Hintergrund>pastell-gelb</Hintergrund>
                <Schrift>schwarz</Schrift>
            </Farben>
            <FirstGenerationDone>false</FirstGenerationDone>
            <History>@changed OLI - Added.</History>
            <InDevelopment>false</InDevelopment>
            <Kommentar></Kommentar>
            <NMRelation>false</NMRelation>
            <Name>Room</Name>
            <Options>
                <Count>0</Count>
            </Options>
            <Panels>
                <Anzahl>1</Anzahl>
                <Panel0>
                    <PanelClass></PanelClass>
                    <PanelNumber>0</PanelNumber>
                    <TabMnemonic>1</TabMnemonic>
                    <TabTitle>1.Daten</TabTitle>
                    <TabToolTipText>Hier k&ouml;nnen Sie die Daten des Objekt warten</TabToolTipText>
                </Panel0>
            </Panels>
            <Spalten>
                <Anzahl>4</Anzahl>
                <Codegenerator>
                    <ActiveInApplication>false</ActiveInApplication>
                    <AdditionalCreateConstraints></AdditionalCreateConstraints>
                    <Codegeneratoroptionen></Codegeneratoroptionen>
                    <Codeverzeichnis>.</Codeverzeichnis>
                    <Codieren>true</Codieren>
                    <DynamicCode>true</DynamicCode>
                    <Inherited>false</Inherited>
                    <Kontextname></Kontextname>
                    <UniqueFormula></UniqueFormula>
                </Codegenerator>
                <Spalte0>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>true</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Id</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>true</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte0>
                <Spalte1>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Ident</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>true</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Building</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <Referenz>
                        <Direction0>UP</Direction0>
                        <Direction1>LEFT</Direction1>
                        <Offset0>25</Offset0>
                        <Offset1>25</Offset1>
                        <Spalte>Id</Spalte>
                        <Tabelle>Building</Tabelle>
                        <Views>
                            <Anzahl>1</Anzahl>
                            <View0>
                                <Direction0>UP</Direction0>
                                <Direction1>LEFT</Direction1>
                                <Name>Main</Name>
                                <Offset0>25</Offset0>
                                <Offset1>25</Offset1>
                                <Points>
                                    <Anzahl>1</Anzahl>
                                    <Point1>
                                        <X>275</X>
                                        <Y>150</Y>
                                    </Point1>
                                </Points>
                            </View0>
                        </Views>
                    </Referenz>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte1>
                <Spalte2>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Boolean</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue>FALSE</IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>Assigned</Name>
                    <NotNull>false</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte2>
                <Spalte3>
                    <AlterInBatch>false</AlterInBatch>
                    <Aufgehoben>false</Aufgehoben>
                    <CanBeReferenced>false</CanBeReferenced>
                    <Disabled>false</Disabled>
                    <Domain>Description</Domain>
                    <Editordescriptor>
                        <Editormember>false</Editormember>
                        <LabelText></LabelText>
                        <MaxCharacters>0</MaxCharacters>
                        <Mnemonic></Mnemonic>
                        <Position>0</Position>
                        <ReferenceWeight>keine</ReferenceWeight>
                        <RessourceIdentifier></RessourceIdentifier>
                        <ToolTipText></ToolTipText>
                    </Editordescriptor>
                    <ForeignKey>false</ForeignKey>
                    <Global>false</Global>
                    <GlobalId>false</GlobalId>
                    <HideReference>false</HideReference>
                    <History>@changed OLI - Added.</History>
                    <IndexSearchMember>false</IndexSearchMember>
                    <Indexed>false</Indexed>
                    <IndividualDefaultValue></IndividualDefaultValue>
                    <Kodiert>false</Kodiert>
                    <Kommentar></Kommentar>
                    <Konsistenz>
                        <Writeablemember>false</Writeablemember>
                    </Konsistenz>
                    <LastModificationField>false</LastModificationField>
                    <ListItemField>false</ListItemField>
                    <Name>RoomNumber</Name>
                    <NotNull>true</NotNull>
                    <PanelNumber>0</PanelNumber>
                    <Parameter></Parameter>
                    <PrimaryKey>false</PrimaryKey>
                    <RemovedStateField>false</RemovedStateField>
                    <SequenceForKeyGeneration></SequenceForKeyGeneration>
                    <SuppressForeignKeyConstraints>false</SuppressForeignKeyConstraints>
                    <TechnicalField>false</TechnicalField>
                    <Transient>false</Transient>
                    <Unique>false</Unique>
                </Spalte3>
            </Spalten>
            <Stereotype>
                <Anzahl>1</Anzahl>
            </Stereotype>
            <Stereotype0>ListObject</Stereotype0>
            <Views>
                <Anzahl>1</Anzahl>
                <View0>
                    <Name>Main</Name>
                    <X>250</X>
                    <Y>375</Y>
                </View0>
            </Views>
        </Tabelle1>
    </Tabellen>
    <Views>
        <Anzahl>1</Anzahl>
        <View0>
            <Beschreibung>Diese Sicht beinhaltet alle Tabellen des Schemas</Beschreibung>
            <Name>Main</Name>
            <ReferenzierteSpaltenAnzeigen>true</ReferenzierteSpaltenAnzeigen>
            <Tabelle0>Building</Tabelle0>
            <Tabelle1>Room</Tabelle1>
            <Tabellenanzahl>2</Tabellenanzahl>
            <TechnischeSpaltenVerstecken>false</TechnischeSpaltenVerstecken>
        </View0>
    </Views>
</Diagramm>
